name: Publish Logger Docker Image

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]
    paths:
      - .github/workflows/publish-logger.yml
      - .github/workflows/publish.yml
      - lib/**
      - logger/**
      - .dockerignore
      - Gemfile
      - Gemfile.lock
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/publish-logger.yml
      - .github/workflows/publish.yml
      - lib/**
      - logger/**
      - .dockerignore
      - Gemfile
      - Gemfile.lock

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      dockerfile_path: ./logger/Dockerfile
      image_name: slack-patron-logger
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
