name: Publish ElasticSearch Docker Image

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]
    paths:
      - .github/workflows/publish-elasticsearch.yml
      - .github/workflows/publish.yml
      - elasticsearch/**
      - .dockerignore
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/publish-elasticsearch.yml
      - .github/workflows/publish.yml
      - elasticsearch/**
      - .dockerignore

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      dockerfile_path: ./elasticsearch/Dockerfile
      docker_context: ./elasticsearch/
      image_name: slack-patron-elasticsearch
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
