name: Publish Viewer Docker Image

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]
    paths:
      - .github/workflows/publish-viewer.yml
      - .github/workflows/publish.yml
      - lib/**
      - viewer/**
      - .dockerignore
      - Gemfile
      - Gemfile.lock
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/publish-viewer.yml
      - .github/workflows/publish.yml
      - lib/**
      - viewer/**
      - .dockerignore
      - Gemfile
      - Gemfile.lock

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      dockerfile_path: ./viewer/Dockerfile
      image_name: slack-patron-viewer
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
